name: ActivityTracker
version: 1.0.0
main: me.AwesomeFishh.ActivityTracker.Main
commands:
    zilanttop:
        description: Get the top 20 most active players!
    zilantactive:
        description: Get the time played of a specific player!
    zilanthelp:
        description: View the help page